# Generated by Django 2.2 on 2020-08-14 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_car', '0003_auto_20200814_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_maintence_trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='In km')),
                ('status', models.CharField(max_length=255)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_car.Cars')),
            ],
        ),
    ]
