# Generated by Django 2.2 on 2020-08-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_car_maintence_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_maintence_trip',
            name='tire1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car_maintence_trip',
            name='tire2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car_maintence_trip',
            name='tire3',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car_maintence_trip',
            name='tire4',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
